#!/usr/bin/env python3
"""Ownership: shared-precheck. Apply a matched preset scenario's env + additional_config to the run.

The presets catalog's ``env`` (HCCL_* etc.) and ``additional_config``
(kv-transfer-config etc.) live in ``knowledge.vendor_preset`` but do NOT
automatically reach the vLLM launch. This script makes them apply:

- ``additional_config`` flags  -> ``config.toml [<engine>.command].others``
  (idempotent merge, backup + TOML validate before writing)
- ``env`` vars                -> ``<run-dir>/launch_env.sh``
  (sourced in the shell before launching ``msmodeling optix``)
  + ``<run-dir>/unset_env.sh`` (cleanup: unsets exactly the keys written,
  to be sourced between rounds / before switching presets so stale env
  cannot leak into later trials and pollute result attribution)

Run after ``collect_context.py`` in Round 0, before the first optix launch.
"""

import argparse
import json
import re
import shlex
import sys
from pathlib import Path

#: others / JSON-container helpers live in common.py — shared with config_writer
#: so a container dict is always serialized the same way (single-quoted JSON) no
#: matter which entry point writes it.
from common import build_others, merge_others


def _load_json(path: Path) -> dict:
    return json.loads(path.read_text(encoding="utf-8"))


def _find_command_section(content: str, engine: str) -> tuple[int, int] | None:
    """Return (start, end) line indices of the ``[<engine>.command]`` section."""
    lines = content.splitlines()
    section_start = None
    for i, line in enumerate(lines):
        stripped = line.strip()
        if stripped == f"[{engine}.command]":
            section_start = i
        elif section_start is not None and stripped.startswith("[") and stripped.endswith("]"):
            return section_start, i
        elif section_start is not None and i == len(lines) - 1:
            return section_start, i + 1
    return None


def update_others_in_toml(content: str, engine: str, new_others: str) -> tuple[str, bool]:
    """Update ``others`` inside ``[<engine>.command]``; returns (content, changed).

    Reads the current ``others`` via tomllib (properly unescaped), computes the
    idempotent merge, and rewrites the line with TOML basic-string escaping.
    """
    try:
        import tomllib
    except ImportError:
        import tomli as tomllib
    current = tomllib.loads(content).get(engine, {}).get("command", {}).get("others", "") or ""
    merged = merge_others(str(current), new_others)
    if merged == current:
        return content, False

    section = _find_command_section(content, engine)
    if section is None:
        return content, False
    start, end = section
    lines = content.splitlines()
    for i in range(start, end):
        stripped = lines[i].strip()
        if stripped.startswith("others") and "=" in stripped:
            # TOML basic string: escape backslash and double-quote
            escaped = merged.replace("\\", "\\\\").replace('"', '\\"')
            indent = lines[i][: len(lines[i]) - len(lines[i].lstrip())]
            lines[i] = f'{indent}others = "{escaped}"'
            return "\n".join(lines), True
    return content, False


def write_launch_env(run_dir: Path, env: dict) -> Path:
    """Write ``export KEY=VALUE`` lines to <run-dir>/launch_env.sh and the
    matching cleanup script <run-dir>/unset_env.sh.

    unset_env.sh unsets exactly the keys written by this script, so a run can
    be cleaned up between rounds or before switching presets — stale env vars
    would otherwise silently leak into later trials and pollute results.
    """
    path = run_dir / "launch_env.sh"
    unset_path = run_dir / "unset_env.sh"
    # launch_env.sh 会被 trial 执行链 source：值必须 shell-quote、key 必须是合法
    # 标识符，否则元字符（; ` $ | & 等）会造成命令注入
    valid: list[tuple[str, str]] = []
    for k, v in sorted(env.items()):
        if v in (None, ""):
            continue
        if not re.fullmatch(r"[A-Za-z_][A-Za-z0-9_]*", k):
            print(f"WARNING: 跳过非法环境变量名: {k}")
            continue
        valid.append((k, str(v)))
    if not valid:
        for p in (path, unset_path):
            if p.exists():
                p.unlink()
        return path
    lines = ["#!/usr/bin/env bash", "# Auto-generated by apply_launch_config.py from presets", ""]
    lines += [f"export {k}={shlex.quote(v)}" for k, v in valid]
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    unset_lines = [
        "#!/usr/bin/env bash",
        "# Auto-generated by apply_launch_config.py — cleanup counterpart of launch_env.sh.",
        "# Source between rounds / before switching presets to avoid stale env leaking",
        "# into later trials (result attribution requires candidate params to be the",
        "# only varying factor).",
        "",
    ]
    unset_lines += [f"unset {k}" for k, _ in valid]
    unset_path.write_text("\n".join(unset_lines) + "\n", encoding="utf-8")
    return path


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Apply preset env + additional_config to the launch.")
    parser.add_argument("--run-dir", required=True, help="optix-assistant run dir (has context.json).")
    parser.add_argument("--config", default="", help="config.toml path (auto-discovers optix/config.toml).")
    parser.add_argument("--dry-run", action="store_true", help="Preview changes without writing.")
    parser.add_argument(
        "--env",
        action="append",
        default=[],
        metavar="KEY=VALUE",
        help="额外环境变量（可重复），合并进 launch_env.sh（如 ASCEND_RT_VISIBLE_DEVICES=0,1）",
    )
    args = parser.parse_args(argv)

    run_dir = Path(args.run_dir)
    ctx_path = run_dir / "context.json"
    if not ctx_path.exists():
        print(f"ERROR: context.json not found at {ctx_path}")
        return 2
    context = _load_json(ctx_path)
    vp = (context.get("knowledge") or {}).get("vendor_preset") or {}
    if not vp:
        print("INFO: 无 vendor_preset（未命中 presets），跳过 additional_config 应用（--env 仍会写入）")

    engine = (context.get("engine") or "vllm").lower()
    config_path = Path(args.config) if args.config else _find_config_toml()
    if config_path is None or not config_path.exists():
        print("WARNING: config.toml 未找到，跳过 additional_config 写入（env 仍生成）")
        config_path = None

    # 1. additional_config -> [<engine>.command].others
    add = dict(vp.get("additional_config") or {})
    # --- Container completeness: vLLM JSON containers are atomic — e.g.
    # speculative-config with `method` REQUIRES num_speculative_tokens at the
    # pydantic layer (speculative.py _verify_args), independent of any n_predict
    # fallback that only runs after model load. The preset authors split such
    # required keys across additional_config (method) and params
    # (num_speculative_tokens); params is consumed by collect_context into the
    # search space (candidate-only path) and never reaches this static `others`
    # channel, so the baseline launch got an incomplete container and vLLM
    # rejected it. Merge required sibling keys from the SAME scenario's params
    # into the container here so the static channel is self-valid; candidate
    # search-side values still override this base via custom_command merge.
    for _key in ("speculative-config",):
        _cont = add.get(_key)
        if not isinstance(_cont, dict):
            continue
        if "method" in _cont and "num_speculative_tokens" not in _cont:
            _ns = (vp.get("params") or {}).get("num_speculative_tokens")
            if _ns not in (None, ""):
                _cont["num_speculative_tokens"] = _ns
    others = build_others(add)
    if others and config_path is not None:
        original = config_path.read_text(encoding="utf-8")
        updated, changed = update_others_in_toml(original, engine, others)
        if args.dry_run:
            print(f"[DRY RUN] 会写入 {config_path} 的 [{engine}.command].others: {others}")
        elif changed and updated != original:
            try:
                import tomllib
            except ImportError:
                import tomli as tomllib
            try:
                tomllib.loads(updated)
            except ValueError as exc:
                print(f"ERROR: 更新后 config.toml 无法解析: {exc}")
                return 1
            backup = config_path.with_suffix(".toml.bak")
            backup.write_text(original, encoding="utf-8")
            config_path.write_text(updated, encoding="utf-8")
            print(f"✓ {config_path} 已更新 others: {others}")
        else:
            print("INFO: others 已包含这些 flag，无需更新")
    elif others:
        print("INFO: additional_config 存在但 config.toml 不可用，未写入 others")

    # 2. env -> launch_env.sh（vendor preset env + 用户显式 --env，用户值优先）
    env = dict(vp.get("env") or {})
    for item in args.env:
        if "=" in item:
            key, value = item.split("=", 1)
            env[key.strip()] = value.strip()
    if env:
        path = write_launch_env(run_dir, env)
        print(f"✓ launch_env.sh 已生成: {path}")
        print(f"✓ unset_env.sh 已生成: {path.parent / 'unset_env.sh'}（轮间/切 preset 前务必 source 清理）")
        if args.env:
            print(f"  含用户显式 env: {', '.join(sorted(args.env))}")
    return 0


def _find_config_toml() -> Path | None:
    """Auto-discover config.toml: CWD first, then walk up from the skill dir.

    CWD is the primary anchor (agent runs from the repo root); ``__file__``
    fallback covers global skill installs that happen to sit inside a repo.
    """
    cwd_candidate = Path.cwd() / "optix" / "config.toml"
    if cwd_candidate.exists():
        return cwd_candidate
    candidate = Path(__file__).resolve().parent.parent
    for _ in range(6):
        if (candidate / ".git").is_dir() or (candidate / ".agent_optimizer").is_dir():
            p = candidate / "optix" / "config.toml"
            if p.exists():
                return p
        parent = candidate.parent
        if parent == candidate:
            break
        candidate = parent
    return None


if __name__ == "__main__":
    sys.exit(main())
