"""Text-generate runner adapter.

Phase B: the heavy simulation runs in a ``runners._worker`` SUBPROCESS (spawned
by ``runners._subprocess.run_module_subprocess``). The worker calls
``execute(params)`` below, which builds a ``ModelRunner``, runs inference, prints
the CLI-style logs (banner via ``cli.logo.print_logo`` + the result table via
``metrics.print_info``), and returns the serialized envelope. The adapter's
``run()`` is now a thin spawner; the job log gets the worker's streamed stdout,
and the process can be hard-killed for prompt cancel.

``ModelRunner.run`` returns a ``ModelRunnerMetrics`` dataclass; ``execute``
serializes its fields into the persisted envelope (mirroring the dict
``dump_json`` builds at ``model_runner.py:338-357``).
"""

from __future__ import annotations

from typing import Any, Callable

from models.entities import ResultRecord
from runners._multicase import resolve_model_id_path


def _metrics_to_envelope(metrics: Any) -> dict[str, Any]:
    """Serialize ``ModelRunnerMetrics`` fields (mirror dump_json payload)."""
    breakdowns = getattr(metrics, "breakdowns", {}) or {}
    breakdowns_percent: dict[str, dict[str, float]] = {}
    for name, breakdown in breakdowns.items():
        try:
            total = sum(breakdown.values())
        except (TypeError, ValueError):
            continue
        if total == 0:
            continue
        breakdowns_percent[name] = {k: round(v * 100 / total, 4) for k, v in breakdown.items()}

    return {
        "batch_size": getattr(metrics, "batch_size", None),
        "run_time_s": getattr(metrics, "run_time_s", None),
        "execution_time_s": dict(getattr(metrics, "execution_time_s", {}) or {}),
        "tps_per_model": dict(getattr(metrics, "tps_per_model", {}) or {}),
        "memory_gb": {
            "total_device": getattr(metrics, "total_device_memory_gb", None),
            "model_weight": getattr(metrics, "model_weight_size_gb", None),
            "peak_usage": getattr(metrics, "peak_memory_usage_gb", None),
            "kv_cache": getattr(metrics, "kv_cache_size_gb", None),
            "kv_cache_per_token": getattr(metrics, "kv_cache_per_token_gb", None),
            "model_activation": getattr(metrics, "model_activation_size_gb", None),
            "reserved": getattr(metrics, "reserved_memory_gb", None),
            "available": getattr(metrics, "device_memory_available_gb", None),
        },
        "breakdowns_raw": {k: dict(v) for k, v in breakdowns.items()},
        "breakdowns_percent": breakdowns_percent,
        "perf_model_name": getattr(metrics, "perf_model_name", None),
    }


def _as_list(value: Any) -> list:
    """Normalize a multi-select value (list | str | None) into a list."""
    if value is None:
        return []
    if isinstance(value, list):
        return [v for v in value if v is not None]
    return [value]


def _parse_int_list(value: Any) -> list[int]:
    """Parse a free-text comma/space list (or a real list / single int) into ints.

    Re-raises a readable ``ValueError`` (carrying the bad value) instead of the
    raw ``int()`` message, so the submit-time preflight can surface it as a 4xx.
    """
    if value is None:
        return []
    if isinstance(value, list):
        try:
            return [int(v) for v in value]
        except (TypeError, ValueError):
            raise ValueError(f"invalid integer list: {value!r}") from None
    if isinstance(value, int):
        return [value]
    parts = [p for p in str(value).replace(",", " ").split() if p]
    try:
        return [int(p) for p in parts]
    except (TypeError, ValueError):
        raise ValueError(f"invalid integer list: {value!r}") from None


def _extract_op_breakdown(
    rt: Any,
    perf_model: str,
    dump_input_shapes: bool,
    dump_op_bound_results: bool,
) -> list[dict[str, Any]]:
    """Extract rich operator-level data with bound and input_shapes.

    Mirrors the CLI table generated by ``Runtime._aggregate_average_table_data``
    so the frontend can render Bound / Input Shapes columns.
    """
    if not rt:
        return []

    try:
        aggregated = rt._aggregate_average_table_data(
            first_model=perf_model,
            group_by_input_shapes=dump_input_shapes,
            dump_op_bound_results=dump_op_bound_results,
        )
        sorted_items = rt._sort_average_table_items(aggregated, perf_model)
        rows: list[dict[str, Any]] = []

        for key, data in sorted_items:
            total_s = data.total_runtimes.get(perf_model, 0)
            row: dict[str, Any] = {
                "name": key.op_name,
                "bound": key.bound or None,
                "input_shapes": key.input_shapes or None,
                "total_s": total_s,
                "avg_s": total_s / data.count if data.count > 0 else 0,
                "calls": data.count,
            }

            if dump_op_bound_results:
                components = data.bound_components.get(perf_model, {})
                total = sum(components.values()) or 1
                row["bound_pct"] = {
                    "memory": components.get("memory", 0) / total * 100,
                    "comm": components.get("communication", 0) / total * 100,
                    "mma": components.get("mma", 0) / total * 100,
                    "gp": components.get("gp", 0) / total * 100,
                }

            rows.append(row)

        return rows
    except Exception:
        return []


# Fields expanded into the multi-case cartesian product (Phase D2).
_MULTI_CASE_FIELDS = (
    "device",
    "num_queries",
    "quantize_linear_action",
    "quantize_attention_action",
    "tp_size",
)


def _expand_cases(params: dict[str, Any], *, max_cases: int | None = None) -> list[dict[str, Any]]:
    """Expand the 5 multi-case fields into the cartesian product of concrete
    case param dicts (each overrides the 5 with a single value). Single-value
    submits collapse to one case (backward compatible).

    ``max_cases`` overrides the hardcoded ``MAX_CASES`` limit. If ``None``,
    the limit is read from ``params["max_search_combinations"]`` (if present);
    if that's also absent, no limit is enforced.
    """
    import itertools

    sources = {
        "device": _as_list(params.get("device")) or [params.get("device")],
        "num_queries": _parse_int_list(params.get("num_queries")) or [params.get("num_queries")],
        "quantize_linear_action": _as_list(params.get("quantize_linear_action"))
        or [params.get("quantize_linear_action")],
        "quantize_attention_action": _as_list(params.get("quantize_attention_action"))
        or [params.get("quantize_attention_action")],
        "tp_size": _parse_int_list(params.get("tp_size")) or [params.get("tp_size")],
    }
    # Determine the case limit: explicit arg > params > no limit
    limit = max_cases if max_cases is not None else params.get("max_search_combinations")
    # Cap the cartesian product incrementally so a runaway form can't fan out
    # into thousands of sequentially-run cases.
    if limit is not None:
        total = 1
        for key in _MULTI_CASE_FIELDS:
            total *= len(sources[key])
            if total > limit:
                raise ValueError(f"too many cases: {total} > {limit}")
    cases: list[dict[str, Any]] = []
    for combo in itertools.product(*(sources[k] for k in _MULTI_CASE_FIELDS)):
        case = dict(params)
        for key, val in zip(_MULTI_CASE_FIELDS, combo):
            case[key] = val
        cases.append(case)
    return cases


def _run_one_case(params: dict[str, Any]) -> dict[str, Any]:
    """Run a single (already concrete) text-gen case; return its record dict."""
    from tensor_cast.core.input_generator import generate_inputs
    from tensor_cast.core.model_runner import ModelRunner

    user_input = _build_user_input(params)
    runner = ModelRunner(user_input)
    # Capture the raw Runtime via the observer (per examples/
    # text_generate_api_example.py) so we can aggregate its event_list into the
    # structured per-op table — metrics.runtime_event_list can be empty.
    runtime_holder: dict[str, Any] = {}

    def _capture_runtime(rt: Any) -> None:
        runtime_holder["rt"] = rt

    # Use the SAME input generator as the CLI (`generate_inputs`) so the web UI
    # op breakdown matches `python -m cli.inference.text_generate` op-for-op.
    # The ModelRunner default (`generate_inputs_varlen`) has a minor asymmetry
    # with the CLI in pure-decode batches: it builds a `selected_token_indices`
    # tensor where the CLI passes `None`, which causes the sampler/lm_head to
    # emit an extra `aten.index.Tensor` op (~2 µs) that the CLI does not.
    metrics = runner.run_inference(
        generate_inputs_func=generate_inputs,
        runtime_observer=_capture_runtime,
    )
    metrics.print_info()  # CLI result table (stdout) -> captured

    envelope = _metrics_to_envelope(metrics)
    perf_model = next(iter(metrics.execution_time_s), None) or "analytic"
    rt = runtime_holder.get("rt")
    # Extract rich operator-level data (replaces the old simple format)
    dump_input_shapes = params.get("dump_input_shapes", False)
    dump_op_bound_results = params.get("dump_op_bound_results", False)
    op_breakdown = _extract_op_breakdown(rt, perf_model, dump_input_shapes, dump_op_bound_results)
    envelope["op_breakdown"] = op_breakdown
    envelope["dump_input_shapes"] = dump_input_shapes
    envelope["dump_op_bound_results"] = dump_op_bound_results
    return {
        "config": {
            "device": params.get("device"),
            "model_id": params.get("model_id"),
            "num_devices": params.get("num_devices", 1),
            "num_queries": params.get("num_queries"),
            "quantize_linear_action": params.get("quantize_linear_action"),
            "quantize_attention_action": params.get("quantize_attention_action"),
            "tp_size": params.get("tp_size"),
        },
        "summary": {
            "run_time_s": envelope.get("run_time_s"),
            "tps_per_model": envelope.get("tps_per_model"),
        },
        "tables": envelope,
    }


def execute(
    params: dict[str, Any],
    *,
    cached_hashes: set[str] | None = None,
    form_schema_version: str | None = None,
    job_id: str | None = None,
) -> tuple[list[dict[str, Any]], list[str]]:
    """Worker-side entry (runs in the ``runners._worker`` subprocess).

    Multi-case (Phase D2): the 5 fields (device / num_queries / quantize_linear
    / quantize_attention / tp) may carry multiple values; their cartesian product
    is run sequentially. A case that raises is recorded as failed and the loop
    continues. Single-value submits run one case.

    Case-level dedup: a case whose ``compute_case_hash`` is in ``cached_hashes``
    is SKIPPED (appended to the returned ``skipped`` list) for the main process to
    reuse from a prior succeeded job. Each run record carries its ``case_hash``.
    Returns ``(records, skipped_hashes)``.
    """
    import traceback

    from cli.logo import print_logo
    from runners._multicase import compute_case_hash

    print_logo()  # CLI banner (stderr) -> captured
    print(f"[case-dedup] text_generate cached_hashes={len(cached_hashes or [])}", flush=True)
    # Resolve a relative model_id against the repo root (cwd is web/backend).
    params = {**params, "model_id": resolve_model_id_path(params.get("model_id"))}
    # Trace path synthesis when chrome_trace is enabled
    from services.trace_store import legacy_hash_path

    def _synth_trace_path(case_params: dict[str, Any], case_hash: str | None) -> None:
        """If chrome_trace is True, replace it with the computed path."""
        if case_params.get("chrome_trace") is True and job_id and case_hash:
            case_params["chrome_trace"] = str(legacy_hash_path(job_id, case_hash))

    cases = _expand_cases(params)

    def _ch(cp: dict[str, Any]) -> str | None:
        return compute_case_hash("text_generate", form_schema_version, cp)

    cached = cached_hashes or set()
    records: list[dict[str, Any]] = []
    skipped: list[str] = []
    from services.capture import capture_case_log
    from runners._cli_command import build_cli_command_string

    # Case divider: a prominent separator line (80 `=` chars) between cases,
    # replacing the `[case i/n]` stamp (which had display issues in some log
    # viewers). Each case's CLI command is still logged, just without the stamp.
    _divider = "\n" + "=" * 80

    # Multi-case expansion summary: the parent process logged the reference
    # command for the ORIGINAL params; list the actual per-case commands here
    # so the job log reflects what will really be executed. No `[case i/n]`
    # stamp.
    if len(cases) > 1:
        print(f"{_divider}", flush=True)
        print(
            f"[text_generate] Expanding into {len(cases)} case(s) based on multi-field values:",
            flush=True,
        )
        for case_params in cases:
            print(f"  {build_cli_command_string('text_generate', case_params)}", flush=True)
        print(flush=True)

    if len(cases) == 1:
        ch = _ch(cases[0])
        if ch and ch in cached:
            print(f"{_divider}", flush=True)
            print(f"Cached (hash {ch[:8]}…)", flush=True)
            skipped.append(ch)
            return records, skipped
        case_params = cases[0]
        _synth_trace_path(case_params, ch)
        with capture_case_log() as buf:
            # Divider + CLI command. No case index label.
            print(f"{_divider}", flush=True)
            print(f"CLI: {build_cli_command_string('text_generate', case_params)}", flush=True)
            print(flush=True)
            rec = _run_one_case(case_params)
        rec["case_hash"] = ch
        rec["case_log"] = buf.getvalue()
        records.append(rec)
        return records, skipped

    for i, case_params in enumerate(cases, 1):
        ch = _ch(case_params)
        if ch and ch in cached:
            print(f"{_divider}", flush=True)
            print(f"Cached (hash {ch[:8]}…)", flush=True)
            skipped.append(ch)
            continue
        _synth_trace_path(case_params, ch)
        cfg = {k: case_params.get(k) for k in _MULTI_CASE_FIELDS}
        buf = None
        try:
            with capture_case_log() as buf:
                # Divider + CLI command + key values. No case index label.
                print(f"{_divider}", flush=True)
                print(f"CLI: {build_cli_command_string('text_generate', case_params)}", flush=True)
                print(
                    f"device={cfg['device']} "
                    f"num_queries={cfg['num_queries']} quant={cfg['quantize_linear_action']} "
                    f"att={cfg['quantize_attention_action']} tp={cfg['tp_size']}",
                    flush=True,
                )
                print(flush=True)
                rec = _run_one_case(case_params)
            rec["case_hash"] = ch
            rec["case_log"] = buf.getvalue()
            records.append(rec)
        except Exception as e:
            traceback.print_exc()
            records.append(
                {
                    "config": {
                        **cfg,
                        "model_id": case_params.get("model_id"),
                        "num_devices": case_params.get("num_devices", 1),
                    },
                    "summary": {"error": str(e)},
                    "tables": {},
                    "case_hash": ch,
                    # Preserve the captured CLI echo + partial output and append the
                    # formatted traceback, so the failed case keeps a case_log
                    # (records without a case_log are dropped at persistence time).
                    "case_log": (buf.getvalue() + traceback.format_exc()) if buf is not None else "",
                }
            )
    return records, skipped


class TextGenerateRunnerAdapter:
    """Adapter implementing ``application/ports/RunnerPort``.

    Thin spawner (Phase B): delegates to ``runners._subprocess.run_module_subprocess``
    which runs ``execute`` in a subprocess, streams its CLI-style output into the
    job log, and hard-kills it on cancel.
    """

    def run(
        self,
        params: dict[str, Any],
        *,
        job_id: str,
        on_progress: Callable[[int | None, str | None], None] | None = None,
        cancel_flag: Callable[[], bool] | None = None,
        cached_hashes: set[str] | None = None,
        form_schema_version: str | None = None,
    ) -> tuple[list[ResultRecord], list[str]]:
        from runners._subprocess import run_module_subprocess

        return run_module_subprocess(
            "text_generate",
            params,
            job_id=job_id,
            on_progress=on_progress,
            cancel_flag=cancel_flag,
            cached_hashes=cached_hashes,
            form_schema_version=form_schema_version,
        )


def _build_user_input(params: dict[str, Any]):
    """Build a ``UserInputConfig`` from frontend params.

    Mirrors the CLI's ``UserInputConfig.from_args`` so **every** form field that
    corresponds to a ``UserInputConfig`` field is forwarded — no restrictive
    keep-set. ``from_args`` applies the 4 CLI<->UIC name maps
    (compile→do_compile, compile_allow_graph_break→allow_graph_break,
    query_length→query_len, num_devices→world_size) and silently drops any key
    that is not a UserInputConfig field.

    The one form field without a UserInputConfig counterpart is
    ``export_empirical_metrics`` (a developer-only post-run JSON export handled
    in ``cli/inference/text_generate.py:main``); it is not a ModelRunner input.
    """
    from types import SimpleNamespace

    from tensor_cast.core.quantization.datatypes import (
        QuantizeAttentionAction,
        QuantizeLinearAction,
    )
    from tensor_cast.core.user_config import UserInputConfig

    renamed = dict(params)
    user_input = UserInputConfig.from_args(SimpleNamespace(**renamed))

    # The frontend sends quantize enums as plain strings; the CLI path receives
    # QuantizeLinearAction enums via argparse ``type=``. Downstream code calls
    # ``action.name``, so coerce any str values back to their StrEnum. The enum
    # classes are StrEnum subclasses, so ``enum_cls(enum_value)`` is idempotent
    # — no ``isinstance`` branch needed; we unconditionally re-coerce.
    for fname, enum_cls in (
        ("quantize_linear_action", QuantizeLinearAction),
        ("quantize_non_expert_linear_action", QuantizeLinearAction),
        ("quantize_attention_action", QuantizeAttentionAction),
    ):
        setattr(user_input, fname, enum_cls(getattr(user_input, fname)))
    return user_input
